<a href="https://colab.research.google.com/github/Ramon-Goveia/DataScience/blob/master/AlgebraLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Álgebra Linear para Ciência de Dados

A álgebra linear é a base para entender muitos algoritmos de machine learning. Alguns tópicos importantes:

Vetores e Matrizes

*   Operações com vetores e matrizes: adição, multiplicação, transposição etc.
*   Autovalores e autovetores
*   Decomposição matricial (LU, QR, SVD)

Este código inclui operações com vetores e matrizes, transposição de matriz, cálculo de autovalores e autovetores, e decomposições matriciais (LU, QR, SVD).

O código utiliza scipy.linalg.lu para a decomposição LU, scipy.linalg.qr para a decomposição QR, e scipy.linalg.svd para a decomposição SVD.

In [6]:
import numpy as np
from scipy.linalg import lu, qr, svd

# Vetores
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Matrizes
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Operações com vetores
v_addition = v1 + v2  # Adição de vetores
v_dot_product = np.dot(v1, v2)  # Produto escalar de vetores
v_cross_product = np.cross(v1, v2)  # Produto vetorial de vetores

# Operações com matrizes
mat_addition = A + B  # Adição de matrizes
mat_multiplication = A.dot(B)  # Multiplicação de matrizes

# Transposição de matriz
A_transpose = A.T

# Autovalores e autovetores
eigenvalues, eigenvectors = np.linalg.eig(A)

# Decomposição matricial
lu_decomposition = lu(A)
qr_decomposition = qr(A)
svd_decomposition = svd(A)

# Impressão dos resultados
print("Operações com Vetores:")
print("Adição de vetores:", v_addition)
print("Produto escalar de vetores:", v_dot_product)
print("Produto vetorial de vetores:", v_cross_product)

print("\nOperações com Matrizes:")
print("Adição de matrizes:")
print(mat_addition)
print("\nMultiplicação de matrizes:")
print(mat_multiplication)

print("\nTransposição de Matriz:")
print(A_transpose)

print("\nAutovalores e Autovetores:")
print("Autovalores:", eigenvalues)
print("Autovetores:")
print(eigenvectors)

print("\nDecomposição Matricial:")
print("LU Decomposition:")
print("P * L * U =", lu_decomposition[0] @ lu_decomposition[1] @ lu_decomposition[2])
print("\nQR Decomposition:")
print("Q * R =", qr_decomposition[0] @ qr_decomposition[1])
print("\nSVD Decomposition:")
print("U * S * V =", svd_decomposition[0] @ np.diag(svd_decomposition[1]) @ svd_decomposition[2])

Operações com Vetores:
Adição de vetores: [5 7 9]
Produto escalar de vetores: 32
Produto vetorial de vetores: [-3  6 -3]

Operações com Matrizes:
Adição de matrizes:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Multiplicação de matrizes:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transposição de Matriz:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Autovalores e Autovetores:
Autovalores: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Autovetores:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Decomposição Matricial:
LU Decomposition:
P * L * U = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

QR Decomposition:
Q * R = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

SVD Decomposition:
U * S * V = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


->

Regressão Linear

*   Ajuste de modelo linear (método dos mínimos quadrados)
*   Cálculo analítico vs computacional
*   Multicolinearidade e redução de dimensionalidade

Este código utiliza a biblioteca scikit-learn em Python para realizar uma análise de Regressão Linear. Ele instancia e ajusta um modelo de Regressão Linear aos dados de entrada (X) e saída (y) usando o método dos mínimos quadrados. Os coeficientes (inclinações) e o intercepto do modelo são impressos como resultados. A interpretação desses parâmetros é essencial para entender a relação linear entre as variáveis de entrada e saída. Além disso, o código menciona a possibilidade de lidar com a multicolinearidade e a redução de dimensionalidade usando o método de Componentes Principais (PCA), embora não demonstre a aplicação completa do PCA neste exemplo.

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
import numpy as np

# Dados de entrada (X) e saída (y)
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([2, 5, 8])

# Instanciação do modelo de Regressão Linear
model = LinearRegression()

# Ajuste do modelo usando o método dos mínimos quadrados
model.fit(X, y)

# Coeficientes (inclinações) do modelo
print("Coeficientes (inclinações):")
print(model.coef_)

# Intercepto do modelo
print("\nIntercepto:")
print(model.intercept_)

# Comentários sobre Regressão Linear:
# - A Regressão Linear modela a relação entre variáveis de entrada (X) e saída (y) assumindo uma relação linear.
# - O ajuste do modelo é realizado utilizando o método dos mínimos quadrados para minimizar a soma dos quadrados dos resíduos.

# Cálculo analítico vs Computacional:
# - O cálculo analítico dos coeficientes e do intercepto pode ser feito de forma direta usando fórmulas matemáticas.
# - No entanto, a implementação computacional, como a fornecida pelo scikit-learn, é eficiente e lida automaticamente com casos mais complexos.

# Multicolinearidade e Redução de Dimensionalidade:
# - A multicolinearidade ocorre quando duas ou mais variáveis de entrada estão altamente correlacionadas.
# - Pode ser necessário lidar com a multicolinearidade para evitar instabilidade nos coeficientes estimados.
# - A redução de dimensionalidade, como a técnica de Componentes Principais (PCA), pode ser usada para tratar multicolinearidade.

# Exemplo de Redução de Dimensionalidade com PCA:
pca = PCA(n_components=1)
X_reduced = pca.fit_transform(X)

# Ajuste do modelo reduzido
model.fit(X_reduced, y)

# Coeficiente (inclinação) do modelo após redução de dimensionalidade
print("\nCoeficiente após redução de dimensionalidade:")
print(model.coef_)

Coeficientes (inclinações):
[0.75 0.75]

Intercepto:
-0.25

Coeficiente após redução de dimensionalidade:
[1.06066017]


->

Regressão Logística

*   Função logística e odds ratio
*   Estimativa de parâmetros via máxima verossimilhança
*   Matriz de confusão e métricas de classificação

Este código em Python utiliza a biblioteca scikit-learn para implementar um modelo de Regressão Logística. A Regressão Logística é uma técnica estatística frequentemente empregada em problemas de classificação binária. O código inclui a definição de dados de entrada e saída, a instância do modelo de Regressão Logística (LogisticRegression), e o ajuste do modelo aos dados de treinamento. Os coeficientes associados às variáveis de entrada e o intercepto são impressos como resultados do ajuste, oferecendo insights sobre a contribuição de cada variável na previsão da classe de saída.

In [8]:
from sklearn.linear_model import LogisticRegression

# Dados de entrada (X) e saída (y)
X = [[0.5], [1.5], [2.5], [3.5]]
y = [0, 0, 1, 1]

# Instanciação do modelo de Regressão Logística
classifier = LogisticRegression()

# Ajuste do modelo usando os dados de treinamento (X, y)
classifier.fit(X, y)

# Coeficiente(s) do modelo (associado(s) à(s) variável(is) de entrada)
print("Coeficiente(s) do modelo:")
print(classifier.coef_)

# Intercepto do modelo (termo independente)
print("\nIntercepto do modelo:")
print(classifier.intercept_)

# Comentários:
# - O código utiliza o scikit-learn para criar um modelo de Regressão Logística.
# - Os dados de entrada (X) representam as variáveis independentes, e os dados de saída (y) representam as classes (0 ou 1).
# - O modelo é treinado (ajustado) utilizando o método da máxima verossimilhança.
# - Os resultados do treinamento, ou seja, os coeficientes e o intercepto, são impressos para análise.
# - A Regressão Logística é comumente usada para problemas de classificação binária.

Coeficiente(s) do modelo:
[[0.95829214]]

Intercepto do modelo:
[-1.9165659]
